# if using RIOTBOOT:
#PROGRAMMER=openocd

# if using Arduino or UF2 bootloaders:
PROGRAMMER=bossa
CFLAGS += -DBOOTLOADER_UF2
include $(RIOTBOARD)/common/samdx1-arduino-bootloader/Makefile.include

include $(RIOTMAKE)/boards/sam0.inc.mk
